---
- name: Build and Push Docker Image
  hosts: your_target_host
  become: yes

  vars:
    github_repo_url: "https://M95kandan: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@github.com/M95kandan/test_website.git "
    dockerhub_username: "M95kandan"
    dockerhub_password: "M#95kandan"
    dockerhub_repository: "m95kandan/website"
    docker_image_tags:
      - "latest"
      - "v1.0"

  tasks:
    - name: Clone private GitHub repository
      git:
        repo: "{{ github_repo_url }}"
        dest: "./"
     

    - name: Build Docker image
      docker_build:
        path: "/path/to/local/repository"
        tag: "{{ dockerhub_username }}/{{ dockerhub_repository }}:{{ docker_image_tag }}"
      

    - name: Log in to Docker Hub
      docker_login:
        registry_url: "https://index.docker.io/v1/"
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Docker image to Docker Hub
      docker_image:
        name: "{{ dockerhub_username }}/{{ dockerhub_repository }}:{{ docker_image_tag }}"
        push: yes
      
