---
- name: Build and Push Docker Image
  hosts: docker_host
  become: yes

  vars:
    docker_image_tags:
      - "{{ build_number_tag }}"
      - "latest"

  tasks:
    - name: Install Docker package
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Copy Dockerfile from Jenkins workspace to the temporary directory
      copy:
        src: "/home/ec2-user/jenkins-IAC/workspace/CI/mk_website/Dockerfile"
        dest: "/tmp/Dockerfile"

    - name: Build and tag Docker image
      command: "docker build -t {{ dockerhub_repository }}:{{ item }} /tmp"
      become: yes
      loop: "{{ docker_image_tags }}"

    - name: Log in to Docker Hub
      command: "docker login -u {{ dockerhub_username }} -p {{ dockerhub_password }}"
      become: yes

    - name: Push Docker images to Docker Hub
      command: "docker push {{ dockerhub_repository }}:{{ item }}"
      become: yes
      loop: "{{ docker_image_tags }}"
